name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 1.4.0
publish_to: none

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  cupertino_icons: 1.0.5
  flutter:
    sdk: flutter
  provider: 6.0.3
  video_player: 2.6.1
  wakelock: 0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1

flutter:
  uses-material-design: true
